#!/usr/bin/env python3
"""Emit LaTeX-ready versions of the paper's headline tables.

Inputs:  aggregated publication_metrics.csv produced by the campaign.
Outputs: table_II_ablation.tex, table_V_significance.tex under the
         LaTeX source tree.
"""
from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parent))
from statistics import bootstrap_ci, pairwise_comparison_table  # noqa: E402


ABLATION_CONFIGS = ["baseline", "l1", "mpc5", "fullstack"]
SCENARIOS = ["A_nominal", "B_single_15s", "C_dual_5s",
             "D_dual_10s", "E_cascade_3fault"]
METRICS = [
    ("rms_error",       "RMS $e_p$ [m]"),
    ("peak_tension",    "peak $T$ [N]"),
    ("rms_sigma_T",     "RMS $\\sigma_T$ [N]"),
    ("qp_solve_us_p99", "QP $p_{99}$ [µs]"),
]


def fmt_ci(mean: float, lo: float, hi: float, digits: int = 2) -> str:
    if np.isnan(mean):
        return "---"
    return f"{mean:.{digits}f} [{lo:.{digits}f}, {hi:.{digits}f}]"


def table_ablation(df: pd.DataFrame, path: Path) -> None:
    with path.open("w") as f:
        f.write("% autogenerated by Research/analysis/ieee/build_tables.py\n")
        f.write("\\begin{table}[t]\n\\centering\n")
        f.write("\\caption{Primary ablation matrix; mean with 95\\% bootstrap CI.}\n")
        f.write("\\label{tab:ablation}\n\\footnotesize\n")
        f.write("\\begin{tabular}{l" + "c" * (len(METRICS)) + "}\n\\toprule\n")
        f.write("config & " + " & ".join(lbl for _, lbl in METRICS) + " \\\\\n")
        f.write("\\midrule\n")
        for cfg in ABLATION_CONFIGS:
            row = [cfg]
            for metric, _ in METRICS:
                samples = df[df.config == cfg][metric].dropna().values
                ci = bootstrap_ci(samples)
                row.append(fmt_ci(ci.mean, ci.lo, ci.hi))
            f.write(" & ".join(row) + " \\\\\n")
        f.write("\\bottomrule\n\\end{tabular}\n\\end{table}\n")


def table_significance(df: pd.DataFrame, path: Path) -> None:
    rows = []
    for metric, label in METRICS:
        comp = pairwise_comparison_table(
            df, metric, ABLATION_CONFIGS,
            pair_by=["scenario", "seed"])
        comp["metric"] = label
        rows.append(comp)
    full = pd.concat(rows, ignore_index=True) if rows else pd.DataFrame()
    with path.open("w") as f:
        f.write("% autogenerated by Research/analysis/ieee/build_tables.py\n")
        f.write("\\begin{table}[t]\n\\centering\n")
        f.write("\\caption{Pairwise Wilcoxon tests (BH-corrected, FDR 0.05).}\n")
        f.write("\\label{tab:significance}\n\\footnotesize\n")
        f.write("\\begin{tabular}{llrrrr}\n\\toprule\n")
        f.write("metric & pair & mean diff & $p$ & Cohen's $d$ & BH \\\\\n")
        f.write("\\midrule\n")
        for _, r in full.iterrows():
            pair = f"{r.config_a} vs {r.config_b}"
            bh = "\\checkmark" if r.bh_pass else "---"
            f.write(f"{r.metric} & {pair} & {r.mean_diff:.3g} & "
                    f"{r.p_wilcoxon:.2e} & {r.cohen_d:+.2f} & {bh} \\\\\n")
        f.write("\\bottomrule\n\\end{tabular}\n\\end{table}\n")


def main() -> None:
    if len(sys.argv) < 3:
        print(__doc__)
        sys.exit(1)
    metrics_csv = Path(sys.argv[1])
    out_dir = Path(sys.argv[2])
    out_dir.mkdir(parents=True, exist_ok=True)
    df = pd.read_csv(metrics_csv)
    table_ablation(df, out_dir / "table_II_ablation.tex")
    table_significance(df, out_dir / "table_V_significance.tex")


if __name__ == "__main__":
    main()
