#!/usr/bin/env python3
"""Emit LaTeX-ready versions of the paper's headline tables.

Inputs:  aggregated publication_metrics.csv produced by the campaign.
Output:  table_II_ablation.tex under the LaTeX source tree.

One run per configuration cell (the campaign is deterministic), so
the table reports per-scenario values directly; no inferential test
is attached.
"""
from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pandas as pd


ABLATION_CONFIGS = ["baseline", "l1", "mpc5", "fullstack"]
SCENARIOS = ["A_nominal", "B_single_15s", "C_dual_5s",
             "D_dual_10s", "E_cascade_3fault"]
METRICS = [
    ("rms_error",       "RMS $e_p$ [m]"),
    ("peak_tension",    "peak $T$ [N]"),
    ("rms_sigma_T",     "RMS $\\sigma_T$ [N]"),
    ("qp_solve_us_p99", "QP $p_{99}$ [\\textmu s]"),
]


def fmt(v: float, digits: int = 2) -> str:
    if v is None or (isinstance(v, float) and np.isnan(v)):
        return "---"
    return f"{float(v):.{digits}f}"


def table_ablation(df: pd.DataFrame, path: Path) -> None:
    with path.open("w") as f:
        f.write("% autogenerated by Research/analysis/ieee/build_tables.py\n")
        f.write("\\begin{table}[t]\n\\centering\n")
        f.write("\\caption{Primary ablation. One deterministic run per cell; "
                "value is averaged across the five scenarios.}\n")
        f.write("\\label{tab:ablation}\n\\footnotesize\n")
        f.write("\\begin{tabular}{l" + "c" * len(METRICS) + "}\n\\toprule\n")
        f.write("config & " + " & ".join(lbl for _, lbl in METRICS) + " \\\\\n")
        f.write("\\midrule\n")
        for cfg in ABLATION_CONFIGS:
            row = [cfg]
            sub = df[df.config == cfg]
            for metric, _ in METRICS:
                if metric in sub.columns:
                    row.append(fmt(sub[metric].mean()))
                else:
                    row.append("---")
            f.write(" & ".join(row) + " \\\\\n")
        f.write("\\bottomrule\n\\end{tabular}\n\\end{table}\n")


def main() -> None:
    if len(sys.argv) < 3:
        print(__doc__)
        sys.exit(1)
    metrics_csv = Path(sys.argv[1])
    out_dir = Path(sys.argv[2])
    out_dir.mkdir(parents=True, exist_ok=True)
    df = pd.read_csv(metrics_csv)
    table_ablation(df, out_dir / "table_II_ablation.tex")


if __name__ == "__main__":
    main()
